package com.iber.portal.model.task;

import java.io.Serializable;
import java.util.Date;

/**
 * @author zengfeiyue
 */
public class TaskPool implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_task_pool.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_task_pool.lpn
     *
     * @mbggenerated
     */
    private String lpn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_task_pool.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_task_pool.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_task_pool.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_task_pool.task_info_id
     *
     * @mbggenerated
     */
    private Integer taskInfoId;

    private Integer version;

    private Integer endParkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_task_pool.id
     *
     * @return the value of e_task_pool.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_task_pool.id
     *
     * @param id the value for e_task_pool.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_task_pool.lpn
     *
     * @return the value of e_task_pool.lpn
     *
     * @mbggenerated
     */
    public String getLpn() {
        return lpn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_task_pool.lpn
     *
     * @param lpn the value for e_task_pool.lpn
     *
     * @mbggenerated
     */
    public void setLpn(String lpn) {
        this.lpn = lpn == null ? null : lpn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_task_pool.status
     *
     * @return the value of e_task_pool.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_task_pool.status
     *
     * @param status the value for e_task_pool.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_task_pool.type
     *
     * @return the value of e_task_pool.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_task_pool.type
     *
     * @param type the value for e_task_pool.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_task_pool.create_time
     *
     * @return the value of e_task_pool.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_task_pool.create_time
     *
     * @param createTime the value for e_task_pool.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_task_pool.task_info_id
     *
     * @return the value of e_task_pool.task_info_id
     *
     * @mbggenerated
     */
    public Integer getTaskInfoId() {
        return taskInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_task_pool.task_info_id
     *
     * @param taskInfoId the value for e_task_pool.task_info_id
     *
     * @mbggenerated
     */
    public void setTaskInfoId(Integer taskInfoId) {
        this.taskInfoId = taskInfoId;
    }


    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getEndParkId() {
        return endParkId;
    }

    public void setEndParkId(Integer endParkId) {
        this.endParkId = endParkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskPool other = (TaskPool) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLpn() == null ? other.getLpn() == null : this.getLpn().equals(other.getLpn()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getTaskInfoId() == null ? other.getTaskInfoId() == null : this.getTaskInfoId().equals(other.getTaskInfoId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLpn() == null) ? 0 : getLpn().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getTaskInfoId() == null) ? 0 : getTaskInfoId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", lpn=").append(lpn);
        sb.append(", status=").append(status);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", taskInfoId=").append(taskInfoId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}