package com.iber.portal.dao.task;

import com.iber.portal.common.Pager;
import com.iber.portal.model.task.TaskPool;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface TaskPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    int insert(TaskPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    int insertSelective(TaskPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    TaskPool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_pool
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskPool record);

    /**
     * 分页查找
     * @param paramMap
     * @return
     */
    List<HashMap> findPage(Map<String, Object> paramMap);

    /**
     * 分页条数
     * @param paramMap
     * @return
     */
    Integer findPageTotalCount(Map<String, Object> paramMap);

    /**
     * 保存到任务池
     * @param lpn
     */
    void saveTaskPoolIgnore(Object lpn);

    /**
     * status='1'
     * @param lpn
     * @return
     */
    Integer findByStatusAndLpn(Object lpn);

    /**
     * 取消任务池的任务
     * 取消规则（未接单的）：
     * 1、任务池已有任务，车辆实际状态是运营，取消这个任务
     * 2、如果是充电任务，车辆已经在充电，补电状态，则取消这个任务
     */
    void cancelTaskPool();
}