package com.iber.portal.dao.task;

import com.iber.portal.model.task.TaskScoreStrategy;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface TaskScoreStrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_score_strategy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_score_strategy
     *
     * @mbggenerated
     */
    int insert(TaskScoreStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_score_strategy
     *
     * @mbggenerated
     */
    int insertSelective(TaskScoreStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_score_strategy
     *
     * @mbggenerated
     */
    TaskScoreStrategy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_score_strategy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskScoreStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_task_score_strategy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskScoreStrategy record);

    /**
     * 分页查找
     * @param paramMap
     * @return
     */
    List<HashMap> findPage(Map<String,Object> paramMap);

    /**
     * 分页总数
     * @param paramMap
     * @return
     */
    Integer findPageTotalCount(Map<String,Object> paramMap);

    /**
     * 获取维修大类
     * @return
     */
    List<Map> getMaintainType();

    /**
     * 根据type cityCode查找
     * @param type
     * @param cityCode
     * @return
     */
    List<TaskScoreStrategy> findByTypeAndCityCode(@Param("type") Integer type,@Param("cityCode") String cityCode,@Param("maintainType") Integer maintainType);

    /**
     *根据type cityCode查找 和里程查找
     * @param type
     * @param cityCode
     * @param minMileage
     * @param maxMileage
     * @return
     */
    List<TaskScoreStrategy> findByTypeAndCityCodeMileage(@Param("type") Integer type, @Param("cityCode") String cityCode, @Param("minMileage") Double minMileage, @Param("maxMileage")Double maxMileage);
}