package com.iber.portal.dao.base;

import com.iber.portal.model.base.Area;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_area
     *
     * @mbggenerated
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_area
     *
     * @mbggenerated
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_area
     *
     * @mbggenerated
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Area record);

    /**
     * 分页查找
     * @param paramMap
     * @return
     */
    List<HashMap> findPage(Map<String,Object> paramMap);

    /**
     * 分页统计
     * @param paramMap
     * @return
     */
    Integer findPageTotalCount(Map<String,Object> paramMap);

    /**
     * 根据城市名称和区域名称查找
     * @param cityCode
     * @param areaName
     * @return
     */
    Area queryByCityCodeAndAreaName(@Param("cityCode") String cityCode,@Param("areaName") String areaName);

    /**
     * 查找绑定的网点
     * @param paramMap
     * @return
     */
    List<HashMap> findAreaParkPage(Map<String,Object> paramMap);

    /**
     * 查找绑定的网点总数
     * @param paramMap
     * @return
     */
    Integer findAreaParkPageTotalCount(Map<String,Object> paramMap);

    /**
     * UnBind
     * @param paramMap
     * @return
     */
    List<HashMap> findUnBindAreaParkPage(Map<String,Object> paramMap);

    /**
     *
     * @param paramMap
     * @return
     */
    Integer findUnBindAreaParkPageTotalCount(Map<String,Object> paramMap);

    /**
     * 根据城市获取区域网点分组
     * @return
     */
    List<HashMap> getAreaGroupByCity();
}