// zh_CN.js
plupload.addI18n({
	'Select files' : '选择图片:',
	'Add files to the upload queue and click the start button.' : '将图片添加到上传队列，然后点击“开始”按钮.',
	'Filename' : '图片名',
	'Status' : '状态',
	'Size' : '大小',
	'Add files' : '添加图片',
	'Stop current upload' : '停止当前图片的上传',
	'Start uploading queue' : '开始上传队列',
	'Uploaded %d/%d files': '上传第 %d/%d个图片',
	'N/A' : 'N/A',
	'Drag files here.' : '拖动图片到这里;',
	'File extension error.': '图片扩展名错误.',
	'File size error.': '图片大小错误.',
	'Init error.': '初始化错误.',
	'HTTP Error.': 'HTTP错误.',
	'Security error.': '安全错误.',
	'Generic error.': '一般错误.',
	'IO error.': 'IO错误.',
	'Stop upload': '停止上传',
	'Add Files': '添加图片',
	'Start upload': '开始上传',
	'%d files queued': '%d 图片列队.'
});